### 회원 가입 
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "test@naver.com",
    "password":"12345"
    ,"aaa":"bbb"
}

### 로그인 
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "test@naver.com",
    "password":"12345"
}

### 로그아웃 
POST http://localhost:3000/auth/signout

### 로그인 되어 있는지 확인
GET http://localhost:3000/auth/whoami

### 세그먼트로 id 로 유저 찾기
GET http://localhost:3000/auth/4

### 쿼리스트링으로 email 유저 찾기 
GET http://localhost:3000/auth?emai1l=11111@naver.com

### 삭제 
DELETE http://localhost:3000/auth/2

### Update 유저 
PATCH http://localhost:3000/auth/3 
Content-Type: application/json


{
    "email": "vvvv2221111@net.com"
}

### Set a color
GET http://localhost:3000/auth/colors/green 

### Get the color
GET http://localhost:3000/auth/colors